services:
  # SQL Server Database
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: servicehub_database
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - servicehub_network
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-C", "-S", "localhost", "-U", "sa", "-P", "${DB_PASSWORD}", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 60s

  # .NET Backend API
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    container_name: servicehub_backend
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "${ASPNETCORE_URLS}"
      CONNECTION_STRING: "Server=database;Database=AppDB;User Id=${DB_USER};Password=${DB_PASSWORD};Encrypt=false;TrustServerCertificate=true;"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      JWT_ISSUER: "${JWT_ISSUER}"
      JWT_AUDIENCE: "${JWT_AUDIENCE}"
      JWT_EXPIRATION_MINUTES: "${JWT_EXPIRATION_MINUTES:-60}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      GOOGLE_REDIRECT_URI: "${GOOGLE_REDIRECT_URI}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
    ports:
      - "5097:5097"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - servicehub_network

    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "${BACKEND_HEALTH_CHECK_URL}"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 40s

  # Node.js Frontend (Astro)
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.frontend
      args:
        PUBLIC_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        PUBLIC_API_URL: ${PUBLIC_API_URL}
    container_name: servicehub_frontend
    environment:
     - NODE_ENV=production
     - PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
     - PUBLIC_API_URL=${PUBLIC_API_URL}
    ports:
      - "4321:4321"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - servicehub_network
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "${FRONTEND_HEALTH_CHECK_URL}"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s

networks:
  servicehub_network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local